### ISSUE TITLE
../hw/arm/apple-silicon/boot.c:35:10: fatal error: 'lzfse.h' file not found #include "lzfse.h"          ^~~~~~~~~

### ISSUE THREAD

**Issue by MudSplasher** [ChefKissInc/QEMUAppleSilicon#29]
when I try to compile it it shows this error../hw/arm/apple-silicon/boot.c:35:10: fatal error: 'lzfse.h' file not found
#include "lzfse.h"
         ^~~~~~~~~

**Comment by VisualEhrmanntraut** [comment]
invalid; install lzfse properly
